[project]
name = "csv-to-phenopacket-demo"
version = "0.1.0"
description = "Demo script to show how to convert a CSV file to a set of Phenopacket Family files"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "phenopackets>=2.0.2.post5",
    "protobuf"
]
